# -*- coding: utf-8 -*-
"""stress_index.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MzkbfePiNowWqtYRswZ90OaRHRnDete
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Load data
df = pd.read_csv("synthetic_cashpulse_data.csv")

# Features to normalize
features_to_scale = [
    "income_drop_pct",
    "balance_drop_pct",
    "emi_to_income_ratio",
    "credit_utilization",
    "failed_autodebit",
    "discretionary_spend_drop"
]

scaler = MinMaxScaler()
df[features_to_scale] = scaler.fit_transform(df[features_to_scale])

print("Features normalized successfully!")

# 1️⃣ Income Stability Index
df["income_stability_index"] = df["income_drop_pct"]

# 2️⃣ Liquidity Strength Index
df["liquidity_strength_index"] = df["balance_drop_pct"]

# 3️⃣ Debt Pressure Index
df["debt_pressure_index"] = (
    df["emi_to_income_ratio"] +
    df["credit_utilization"] +
    df["failed_autodebit"]
) / 3

# 4️⃣ Behavioral Shift Index
df["behavioral_shift_index"] = df["discretionary_spend_drop"]

df["financial_stress_score"] = (
    0.30 * df["income_stability_index"] +
    0.25 * df["liquidity_strength_index"] +
    0.25 * df["debt_pressure_index"] +
    0.20 * df["behavioral_shift_index"]
)

print(df[[
    "customer_id",
    "financial_stress_score"
]].head())

df.to_csv("synthetic_cashpulse_data_with_stress.csv", index=False)

